steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - 'gcr.io/${PROJECT_ID}/social-listening-frontend'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
  - '--build-arg'
  - 'NEXT_PUBLIC_WHATSAPP_API_URL=${_NEXT_PUBLIC_WHATSAPP_API_URL}'
  - '.'
images:
- 'gcr.io/${PROJECT_ID}/social-listening-frontend'
